### ISSUE TITLE
Portfolios 링크 설정

### ISSUE THREAD

**Issue by unk** [grotesq/grotesq.com#7]
포트폴리오 항목은 각각의 페이지가 노션 페이지로 연결되고, 새창으로 연결 되어야 합니다.
현재는 링크 영역으로 구성되어 있지 않아 수정이 필요합니다.

**Comment by nanuruya** [comment]
여전히 연결되어있지 않습니다. 다시 확인 요청드립니다 @jiyeon-kim2
